// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: PrivateOrdersV3Api.proto
// Protobuf Java Version: 4.31.1

package com.mxc.push.common.protobuf;

@com.google.protobuf.Generated
public final class PrivateOrdersV3ApiProto {
  private PrivateOrdersV3ApiProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 31,
      /* patch= */ 1,
      /* suffix= */ "",
      PrivateOrdersV3ApiProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PrivateOrdersV3Api_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PrivateOrdersV3Api_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030PrivateOrdersV3Api.proto\"\216\004\n\022PrivateOr" +
      "dersV3Api\022\n\n\002id\030\001 \001(\t\022\020\n\010clientId\030\002 \001(\t\022" +
      "\r\n\005price\030\003 \001(\t\022\020\n\010quantity\030\004 \001(\t\022\016\n\006amou" +
      "nt\030\005 \001(\t\022\020\n\010avgPrice\030\006 \001(\t\022\021\n\torderType\030" +
      "\007 \001(\005\022\021\n\ttradeType\030\010 \001(\005\022\017\n\007isMaker\030\t \001(" +
      "\010\022\024\n\014remainAmount\030\n \001(\t\022\026\n\016remainQuantit" +
      "y\030\013 \001(\t\022\030\n\020lastDealQuantity\030\014 \001(\t\022\032\n\022cum" +
      "ulativeQuantity\030\r \001(\t\022\030\n\020cumulativeAmoun" +
      "t\030\016 \001(\t\022\016\n\006status\030\017 \001(\005\022\022\n\ncreateTime\030\020 " +
      "\001(\003\022\016\n\006market\030\021 \001(\t\022\023\n\013triggerType\030\022 \001(\005" +
      "\022\024\n\014triggerPrice\030\023 \001(\t\022\r\n\005state\030\024 \001(\005\022\r\n" +
      "\005ocoId\030\025 \001(\t\022\023\n\013routeFactor\030\026 \001(\t\022\020\n\010sym" +
      "bolId\030\027 \001(\t\022\020\n\010marketId\030\030 \001(\t\022\030\n\020marketC" +
      "urrencyId\030\031 \001(\t\022\022\n\ncurrencyId\030\032 \001(\tB;\n\034c" +
      "om.mxc.push.common.protobufB\027PrivateOrde" +
      "rsV3ApiProtoH\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PrivateOrdersV3Api_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PrivateOrdersV3Api_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_PrivateOrdersV3Api_descriptor,
        new java.lang.String[] { "Id", "ClientId", "Price", "Quantity", "Amount", "AvgPrice", "OrderType", "TradeType", "IsMaker", "RemainAmount", "RemainQuantity", "LastDealQuantity", "CumulativeQuantity", "CumulativeAmount", "Status", "CreateTime", "Market", "TriggerType", "TriggerPrice", "State", "OcoId", "RouteFactor", "SymbolId", "MarketId", "MarketCurrencyId", "CurrencyId", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
